language: python

python:
  - 3.9

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - pipenv run flake8
  - pipenv run pytest --cov=pypro
  - cp contrib/env-sample .env

after_success:
  - pipenv run codecov
